#if !canImport(ObjectiveC)
import XCTest

extension swift_test_codecovTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__swift_test_codecovTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(swift_test_codecovTests.__allTests__swift_test_codecovTests),
    ]
}
#endif
